package repository;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
/**
 *
 * @author 22wili03
 */
public class DbConnectionManager {
	
	private static final String DB_NAME = "myDB"; // Change value to your database
	private static final String USER = "root"; // Change value to your user
	private static final String PASSWORD = "root"; // Change value to your password
	//private static final String CONNECTION_URL = "jdbc:postgresql://localhost/" + DB_NAME;
        private static final String CONNECTION_URL = "jdbc:mysql://localhost:3306/" + DB_NAME;
	
	private Connection connection = null;
	private Statement statement = null;
	private ResultSet resultSet = null;
	
	private static DbConnectionManager instance = null;
	
	private DbConnectionManager(){}
	
	public static DbConnectionManager getInstance() {
		if(instance == null) {
			instance = new DbConnectionManager();
		}
		return instance;
	}

	/**
	 * This method creates a connection to the database by a connection URL
	 * and a user name and password.
	 * It is private because all DB specific is contained within this class.	
	 * @return An instance of type java.sql.Connection
	 */
	private Connection getConnection() {
        try {
            connection = DriverManager.getConnection(CONNECTION_URL, USER, PASSWORD);
            System.out.println("Connected to the PostgreSQL server successfully.");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
 
        return connection;
	}
	private Statement getStatement(Connection connection) {
		try{
			statement =  connection.createStatement();
		}
		catch (SQLException e) {
			System.err.println("Could not create Statement");
			System.err.println(e.getMessage());
		}
		return statement;
	}
	/**
	 * Wrapper method to the 'statement'.executeQuery(String sqlString)
	 * A statement needs a connection and is mandatory to be able
	 * to send a query to the DB. This is wrapped to contain all DB 
	 * specific techniques within this class.
	 * This method is one of the few that is exposed as public and it
	 * hides the DB-connection mechanism.
	 * <strong>Because of the bare sql string this method is susceptible to 
	 * SQL-injection and should only be used for read only transactions.</strong> 
	 * @param sqlString The sql string
	 * @return A ResultSet with the result from the SQL query
	 * @throws SQLException 
	 */
	public ResultSet excecuteQuery( String sqlString) throws SQLException {
		return this.getStatement(this.getConnection()).executeQuery(sqlString);
	}
	
	/**
	 * Wrapper method to the 'connection'.prepareStatement(String sqlString)
	 * It hides the DB-connection mechanism but exposes (by public) the prepareStatement
	 * method thus needing only a String (the SQL string) and returning a ResultSet
	 * <strong>This method is not susceptible to SQL-injection and is therefore safe to use
	 * for write operations on the database.<strong>
	 * @param statementString
	 * @return
	 * @throws SQLException
	 */
	public PreparedStatement prepareStatement(String statementString) throws SQLException {
		return this.getConnection().prepareStatement(statementString);
	}
        
        public PreparedStatement prepareStatement(String statementString, int autoGeneratedKeys) throws SQLException {
		return this.getConnection().prepareStatement(statementString, autoGeneratedKeys);
	}
	
	public void close() {
		try{
			if(statement != null) statement.close();
			if(connection != null) connection.close();
			System.out.println("DB Connection closed");
		}catch (SQLException e) {
			System.err.println("Could not close the statement or the connection");
			System.err.println(e.getMessage());
		}
	}
}
